### ISSUE TITLE
Is it possible to pass a objects into the steps like ActivityTestRule or WireMockRule?

### ISSUE THREAD

**Issue by chris-gunawardena** [mauriciotogneri/green-coffee#12]
We have steps that require different mocks and at the moment not sure how to access @Rule objects declared in the main test file. Same goes for context, is there away to access this from the steps definitions?

**Comment by chris-gunawardena** [comment]
Just figured it out. I'm passing it as an param to the constructor of the steps class.

**Comment by mauriciotogneri** [comment]
I'm glad that you are finding the library helpful. Don't hesitate to tell me if you find any issue or you want a specific functionality.
