### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by look416** [mauriciotogneri/green-coffee#14]
Hi,

Is there any chance you will start to support Kotlin? Currently, I tried to use with Kotlin, however, there are several issues with it, such as ````Step Definition not found````

**Comment by mauriciotogneri** [comment]
Hi,

In theory Kotlin has interoperability with Java so everything should work without adding extra support. Can you share the link of your repository so I could take a look at it?

**Comment by look416** [comment]
Hi,

Sorry, it's my side fault, didn't realize there is an error in my code which causes the app to crash before even the test could be initialized.

**Comment by mauriciotogneri** [comment]
No problem, let me know if you have another issue so I can help.
