### ISSUE TITLE
Screenshot does not contain dialogs

### ISSUE THREAD

**Issue by klamborowski** [mauriciotogneri/green-coffee#19]
Hi. I need to take screenshot of failed test with displayed dialog, but unfortunatelly, takeScreenshot method does not handle dialogs. I've find library, which can handle my case (https://github.com/jraska/Falcon), but I can't pass it to GreenCoffeeConfig.

I've written a ScreenshotProvider to add my own takeScreenshot implementation. Please look at the PR #18 , I think it can be also helpful for the other people.

**Comment by mauriciotogneri** [comment]
Hi. Sorry for the late response, I was on vacation. I will try to merge the PR and make a release as soon as possible but it will take a few days. Thanks for the contribution!

**Comment by mauriciotogneri** [comment]
@klamborowski 
Sorry for the late fix, I just released the version 3.3.0. I made a couple of adjustments but it's basically the same changes you did. Thanks a lot for your help!
