### ISSUE TITLE
Incorrect description inside Readme.md

### ISSUE THREAD

**Issue by tomkoptel** [mauriciotogneri/green-coffee#7]
Installation steps state:
`
compile 'com.mauriciotogneri:greencoffee:2.0.0'
`

Should be:
`
androidTestCompile 'com.mauriciotogneri:greencoffee:1.0.0'
`

**Comment by mauriciotogneri** [comment]
Thanks for pointing it out! You were faster than me deploying the new version.

**Comment by tomkoptel** [comment]
I just found that version is `2.0.1`. Just for history reference there is a public page for library located at https://bintray.com/mauriciotogneri/maven/greencoffee/2.0.1

**Comment by mauriciotogneri** [comment]
Yes, I corrected some small stuff from the version 2.0.0 and released a new one. Now all the docs are updated with the latest version. Thanks!
